apiVersion: v1
kind: ReplicationController
metadata:
  name: api
spec:
  replicas: 3
  selector:
    app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: wldev/kubereval.api:1.0
          ports:
            - containerPort: 3000
